#!/usr/bin/env python3
"""Generate the experimental local plugin from canonical MCP skills (stdlib only)."""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "plugins" / "redisctl-mcp"
SKILLS = ("redisctl-setup", "enterprise-health-check", "data-explorer")
VERSION = "0.0.1"
POLICY = '''# Experimental plugin: read-only even if the user's default policy permits writes.
tier = "read-only"
deny_categories = ["destructive"]
deny = ["cloud_raw_api", "enterprise_raw_api", "redis_command", "profile_show"]

[tools]
preset = "essentials"
include = ["get_license_usage", "redis_memory_usage", "redis_json_get", "redis_smembers", "redis_zrange", "redis_lrange", "redis_xrange", "redis_hotkeys"]
'''

GUIDANCE = '''## Plugin safety and discovery

This is an experimental local plugin using an already-installed Rust redisctl-mcp.
Check the plugin server's available tools and call `show_policy` before this
workflow. Map the tool names below to the matching tools exposed by this plugin's
server; clients can namespace them. Do not use a similarly named tool from another
server or silently switch targets. If a tool is unavailable, explain the limitation
and stop that step; do not enable writes or bypass policy.

Use only the target and data scope the user approved. Read-only is not permission
to disclose data: do not sample values or report sensitive identifiers unless the
user requested that scope. Never request credentials in chat or tool arguments,
read credential files/environment values, or provision resources during setup.
For a new profile, guide the user through `redisctl profile init` in their own
terminal, then restart this MCP connection. The companion CLI is a prerequisite
for that flow. Installed plugin skills remain available if the server lacks MCP
resource/prompt support; do not claim the embedded skill index exists on an older
binary. Operational health results do not authorize subsequent changes.

'''


def encode(value):
    return json.dumps(value, indent=2, ensure_ascii=False) + "\n"


def server(root_variable):
    return {
        "type": "stdio",
        "command": "redisctl-mcp",
        "args": [
            "--transport", "stdio", "--read-only=true", "--policy",
            f"${{{root_variable}}}/read-only.toml",
            "--tools", "cloud,enterprise,database,app",
        ],
    }


def generated_files(root=ROOT):
    identity = {
        "name": "redisctl-mcp",
        "version": VERSION,
        "description": "Experimental local Redis management plugin using the Rust redisctl-mcp server.",
        "author": {"name": "Redis", "url": "https://github.com/redis/redisctl"},
        "homepage": "https://redis.github.io/redisctl/mcp/",
        "repository": "https://github.com/redis/redisctl",
        "license": "MIT OR Apache-2.0",
    }
    files = {
        "plugin.json": encode({
            "$schema": "https://agent-plugins.org/schemas/1.0.0/plugin.schema.json",
            **identity,
            "extensions": {"com.openai": {
                "onboardingSkill": "./skills/redisctl-setup/SKILL.md",
                "interface": {"displayName": "redisctl MCP (experimental)",
                              "shortDescription": "Read-only Redis workflows with local profiles"},
            }},
        }),
        "mcp.json": encode({
            "$schema": "https://agent-plugins.org/schemas/1.0.0/mcp.schema.json",
            "mcpServers": {"redisctl": server("PLUGIN_ROOT")},
        }),
        ".claude-plugin/plugin.json": encode(identity),
        ".mcp.json": encode({"mcpServers": {"redisctl": server("CLAUDE_PLUGIN_ROOT")}}),
        "read-only.toml": POLICY,
    }
    for name in SKILLS:
        source = root / "crates" / "redisctl-mcp" / "skills" / name / "SKILL.md"
        markdown = source.read_text(encoding="utf-8")
        if not markdown.startswith("---\n") or "\n---\n" not in markdown[4:]:
            raise ValueError(f"Invalid skill frontmatter: {name}")
        header, body = markdown[4:].split("\n---\n", 1)
        if f"name: {name}" not in header.splitlines():
            raise ValueError(f"Skill identity mismatch: {name}")
        files[f"skills/{name}/SKILL.md"] = (
            "---\n" + header + "\n---\n\n"
            + f"<!-- Generated by plugins/build_plugin.py from crates/redisctl-mcp/skills/{name}/SKILL.md. -->\n\n"
            + GUIDANCE + body.lstrip("\n")
        )
    return files


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if tracked generated files drift")
    args = parser.parse_args()
    drift = []
    targets = {PACKAGE / relative: expected for relative, expected in generated_files().items()}
    # Keep the Rust regression self-contained when Cargo packages the crate.
    targets[ROOT / "crates/redisctl-mcp/tests/fixtures/plugin-read-only.toml"] = POLICY
    for target, expected in targets.items():
        if args.check:
            if not target.is_file() or target.read_text(encoding="utf-8") != expected:
                drift.append(str(target.relative_to(ROOT)))
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(expected, encoding="utf-8")
    if drift:
        parser.exit(1, "Plugin generation drift: " + ", ".join(drift) + "\n")
    print("Plugin generated files are current" if args.check else "Generated experimental redisctl-mcp plugin")


if __name__ == "__main__":
    main()
