//! Per-product example modules: generated once, never overwritten - the file is
//! the user's from the moment it lands, and nothing imports it until they do.
//! Templates carry env names only, never values, so the file is safe to commit.

use std::path::Path;

use crate::change::{Change, Status};
use crate::env::FileAction;
use crate::products::{ProductKey, WiredProduct};
use crate::project::Runtime;
use crate::util::{exists, read_if};

/// Only directories that already exist - no layout is invented for the example.
fn source_dir(cwd: &Path) -> &'static str {
    ["src", "app", "lib"]
        .into_iter()
        .find(|dir| cwd.join(dir).is_dir())
        .unwrap_or(".")
}

struct Flavour {
    ext: &'static str,
    esm: bool,
}

fn node_flavour(cwd: &Path) -> Flavour {
    if exists(cwd, "tsconfig.json") {
        return Flavour {
            ext: "ts",
            esm: true,
        };
    }
    let esm = serde_json::from_str::<serde_json::Value>(
        &read_if(cwd, "package.json").unwrap_or_default(),
    )
    .map(|pkg| pkg["type"] == "module")
    .unwrap_or(true);
    Flavour { ext: "js", esm }
}

fn header(comment: &str, label: &str) -> String {
    [
        format!("{comment} {label} for this project, generated by redisctl init."),
        format!(
            "{comment} This file is yours: edit it, move it, or delete it - nothing imports it until you do."
        ),
        format!(
            "{comment} Credentials come from the environment (see .env), so this file is safe to commit."
        ),
    ]
    .join("\n")
}

const SAFE_ID_JS: &str = r#"// Session and actor ids accept only letters, digits and hyphens - the API rejects a dot
// or an underscore with a 400, so anything derived from a username needs this.
const safeId = (value) => String(value).replace(/[^A-Za-z0-9-]+/g, '-');
"#;

const AGENT_MEMORY_NODE_SDK: &str = r#"import { AgentMemory } from '__PKG__';

// The SDK reads __KEY__ from the environment; the store id is passed in.
const memory = new AgentMemory({
  serverURL: process.env.__URL__,
  storeId: process.env.__ID__,
});

__EXP__ rememberTurn({ sessionId, actorId, text, role = 'USER' }) {
  return memory.addSessionEvent({
    sessionId: safeId(sessionId),
    actorId: safeId(actorId),
    role,
    content: [{ text }],
    createdAt: new Date(),
  });
}

__EXP__ recallSession(sessionId) {
  try {
    return await memory.getSessionMemory(sessionId);
  } catch (err) {
    // A session nobody has written to yet is a 404: that is an empty history, not a fault.
    if (err?.name === 'NotFoundErrorResponseContent' || err?.statusCode === 404) return { events: [] };
    throw err;
  }
}
"#;

const AGENT_MEMORY_TAIL_JS: &str = r#"
// One session per conversation, one actorId per end user: that pairing is what makes
// memory compound across sessions instead of piling up.
"#;

const AGENT_MEMORY_PYTHON: &str = r#"import json
import os
import urllib.error
import urllib.request
from datetime import datetime, timezone

_BASE = os.environ["__URL__"]
_STORE = os.environ["__ID__"]
_KEY = os.environ["__KEY__"]


def _call(path, payload=None):
    request = urllib.request.Request(
        f"{_BASE}/v1/stores/{_STORE}{path}",
        data=json.dumps(payload).encode() if payload is not None else None,
        headers={"Authorization": f"Bearer {_KEY}", "Content-Type": "application/json"},
        method="POST" if payload is not None else "GET",
    )
    try:
        with urllib.request.urlopen(request) as response:
            return json.load(response)
    except urllib.error.HTTPError as error:
        # A session nobody has written to yet is a 404: an empty history, not a fault.
        if error.code == 404 and payload is None:
            return {"events": []}
        raise


def remember_turn(session_id, actor_id, text, role="USER"):
    """Append one conversation turn to session memory."""
    return _call(
        "/session-memory/events",
        {
            "sessionId": session_id,
            "actorId": actor_id,
            "role": role,
            "content": [{"text": text}],
            "createdAt": datetime.now(timezone.utc).isoformat(),
        },
    )


def recall_session(session_id):
    """Read the conversation back, to rebuild context on the next turn."""
    return _call(f"/session-memory/{session_id}")


# One session per conversation, one actor_id per end user: that pairing is what makes
# memory compound across sessions instead of piling up.
# There is no Python SDK for the managed service yet - PyPI's agent-memory-client is for
# the self-hosted Agent Memory Server, a different API - hence plain REST here.
"#;

const LANGCACHE_NODE_SDK: &str = r#"import { LangCache } from '__PKG__';

const cache = new LangCache({
  serverURL: process.env.__URL__,
  cacheId: process.env.__ID__,
  apiKey: process.env.__KEY__,
});

const search = (prompt) => cache.search({ prompt, maxResults: 1 });
const store = (prompt, response) => cache.set({ prompt, response });
"#;

const LANGCACHE_NODE_BODY: &str = r#"
// Search before generating: a semantic hit skips the model call entirely. Raise the
// threshold if answers feel too loosely matched, lower it for a higher hit rate.
__EXP__ cachedCompletion(prompt, generate, { similarityThreshold = 0.9 } = {}) {
  const { data = [] } = await search(prompt);
  const hit = data.find((entry) => entry.similarity >= similarityThreshold);
  if (hit) return { response: hit.response, cached: true };

  const response = await generate();
  await store(prompt, response);
  return { response, cached: false };
}
"#;

const LANGCACHE_PYTHON: &str = r#"import json
import os
import urllib.request

_BASE = os.environ["__URL__"]
_CACHE = os.environ["__ID__"]
_KEY = os.environ["__KEY__"]


def _post(path, payload):
    request = urllib.request.Request(
        f"{_BASE}/v1/caches/{_CACHE}{path}",
        data=json.dumps(payload).encode(),
        headers={"Authorization": f"Bearer {_KEY}", "Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(request) as response:
        return json.load(response)


def cached_completion(prompt, generate, similarity_threshold=0.9):
    """Search before generating: a semantic hit skips the model call entirely.

    Raise the threshold if answers feel too loosely matched, lower it for a higher
    hit rate.
    """
    hits = _post("/entries/search", {"prompt": prompt, "maxResults": 1}).get("data", [])
    for hit in hits:
        if hit.get("similarity", 0) >= similarity_threshold:
            return {"response": hit["response"], "cached": True}

    response = generate()
    _post("/entries", {"prompt": prompt, "response": response})
    return {"response": response, "cached": False}
"#;

fn fill(template: &str, product: &WiredProduct, pkg: &str, esm: bool) -> String {
    template
        .replace("__PKG__", pkg)
        .replace("__URL__", product.spec.env_url)
        .replace("__ID__", product.spec.env_id.unwrap_or_default())
        .replace("__KEY__", product.spec.env_key)
        .replace(
            "__EXP__",
            if esm {
                "export async function"
            } else {
                "async function"
            },
        )
}

fn node_source(product: &WiredProduct, esm: bool) -> String {
    match product.spec.key {
        ProductKey::AgentMemory => {
            let tail = if esm {
                ""
            } else {
                "\nmodule.exports = { rememberTurn, recallSession };\n"
            };
            format!(
                "{SAFE_ID_JS}\n{}{}{tail}",
                fill(
                    AGENT_MEMORY_NODE_SDK,
                    product,
                    "@redis-iris/agent-memory",
                    esm
                ),
                AGENT_MEMORY_TAIL_JS,
            )
        }
        ProductKey::LangCache => {
            let tail = if esm {
                ""
            } else {
                "\nmodule.exports = { cachedCompletion };\n"
            };
            format!(
                "{}{}{tail}",
                fill(LANGCACHE_NODE_SDK, product, "@redis-ai/langcache", esm),
                fill(LANGCACHE_NODE_BODY, product, "", esm),
            )
        }
        ProductKey::ContextRetriever => unreachable!("no template"),
    }
}

fn plan_example(cwd: &Path, runtime: Runtime, product: &WiredProduct) -> Option<FileAction> {
    let stem = match product.spec.key {
        ProductKey::AgentMemory => "agent-memory",
        ProductKey::LangCache => "langcache",
        // The coding agent uses the MCP tools; there is nothing to demonstrate.
        ProductKey::ContextRetriever => return None,
    };
    let dir = source_dir(cwd);
    let (name, comment, source) = match runtime {
        Runtime::Node => {
            let flavour = node_flavour(cwd);
            (
                format!("redis-{stem}.{}", flavour.ext),
                "//",
                node_source(product, flavour.esm),
            )
        }
        Runtime::Python => {
            let template = match product.spec.key {
                ProductKey::AgentMemory => AGENT_MEMORY_PYTHON,
                _ => LANGCACHE_PYTHON,
            };
            (
                format!("redis_{}.py", stem.replace('-', "_")),
                "#",
                fill(template, product, "", false),
            )
        }
        _ => return None,
    };
    let rel = if dir == "." {
        name
    } else {
        format!("{dir}/{name}")
    };
    if exists(cwd, &rel) {
        return Some(FileAction::Kept {
            rel,
            note: "existing file left untouched".to_string(),
        });
    }
    Some(FileAction::Write {
        rel,
        content: format!("{}\n\n{source}", header(comment, product.label())),
        status: Status::Created,
        note: format!(
            "{} example - nothing imports it; edit or delete it",
            product.label()
        ),
    })
}

/// Plan the example modules for this run's products; the note is the one
/// `--no-example` ledger line (recorded only when there was something to skip).
pub(crate) fn plan_examples(
    cwd: &Path,
    runtime: Runtime,
    products: &[WiredProduct],
    no_example: bool,
) -> (Vec<FileAction>, Option<Change>) {
    if no_example {
        let note = (!products.is_empty())
            .then(|| Change::new("examples", Status::Skipped, "--no-example"));
        return (Vec::new(), note);
    }
    let actions = products
        .iter()
        .filter_map(|product| plan_example(cwd, runtime, product))
        .collect();
    (actions, None)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::products::{ProductRequest, wire};

    fn wired(dir: &Path) -> Vec<WiredProduct> {
        wire(
            dir,
            &[
                ProductRequest {
                    key: ProductKey::AgentMemory,
                    url: "https://m".into(),
                    id: Some("store-123".into()),
                },
                ProductRequest {
                    key: ProductKey::LangCache,
                    url: "https://l".into(),
                    id: Some("cache-456".into()),
                },
                ProductRequest {
                    key: ProductKey::ContextRetriever,
                    url: "https://mcp".into(),
                    id: None,
                },
            ],
            None,
            false,
            &|_| None,
        )
        .unwrap()
    }

    #[test]
    fn node_examples_carry_env_names_never_values_and_skip_mcp_products() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("package.json"), r#"{"type":"module"}"#).unwrap();
        let (actions, note) = plan_examples(dir.path(), Runtime::Node, &wired(dir.path()), false);
        assert!(note.is_none());
        let rels: Vec<_> = actions.iter().map(|a| a.preview().subject).collect();
        assert_eq!(rels, ["redis-agent-memory.js", "redis-langcache.js"]);
        let FileAction::Write { content, .. } = &actions[0] else {
            panic!("expected write");
        };
        assert!(
            content.contains("process.env.AGENT_MEMORY_STORE_ID"),
            "{content}"
        );
        assert!(content.contains("yours: edit it, move it, or delete it"));
        assert!(!content.contains("store-123"), "{content}");
        assert!(content.contains("export async function rememberTurn"));
    }

    #[test]
    fn an_existing_example_is_kept_untouched() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("redis_langcache.py"), "# mine now\n").unwrap();
        let (actions, _) = plan_examples(dir.path(), Runtime::Python, &wired(dir.path()), false);
        let kept = actions
            .iter()
            .find(|a| a.preview().subject == "redis_langcache.py")
            .unwrap();
        assert!(matches!(kept, FileAction::Kept { .. }));
        kept.perform(dir.path()).unwrap();
        assert_eq!(
            std::fs::read_to_string(dir.path().join("redis_langcache.py")).unwrap(),
            "# mine now\n"
        );
    }

    #[test]
    fn no_example_skips_with_one_note_and_examples_land_in_src_when_it_exists() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::create_dir(dir.path().join("src")).unwrap();
        let products = wired(dir.path());
        let (actions, note) = plan_examples(dir.path(), Runtime::Node, &products, true);
        assert!(actions.is_empty());
        assert_eq!(note.unwrap().note, "--no-example");
        let (actions, _) = plan_examples(dir.path(), Runtime::Node, &products, false);
        assert_eq!(actions[0].preview().subject, "src/redis-agent-memory.js");
    }
}
